language: python

python:
- 2.7

before_install:
- CONDA_INST=$HOME/miniconda2
- echo -n "Downloading conda..."
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
- echo "Done!"
- bash Miniconda-latest-Linux-x86_64.sh -b -p $CONDA_INST -f
- export PATH=$CONDA_INST/bin:$PATH
- conda config --set always_yes yes --set changeps1 no
- conda info -a

install:
- pip install coveralls
- pip install click
- pip install pytest-cov
- conda install pandas
- pip install mock==2.0

script:
- py.test tests -s

after_success:
- coveralls
