language: python
python:
- 2.7
before_install:
- echo "127.0.1.1 "`hostname` | sudo tee /etc/hosts
- CONDA_INST=$HOME/miniconda2
- echo -n "Downloading conda... "
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
- echo "Done!"
- bash Miniconda-latest-Linux-x86_64.sh -b -p $CONDA_INST -f
- export PATH=$CONDA_INST/bin:$PATH
- conda config --set always_yes yes --set changeps1 no
- conda info -a
- conda install conda-build anaconda-client
script: echo -e "1\t1\t1" | python bed_to_regions.py
after_success:
- conda config --set anaconda_upload yes
- anaconda login --username $ANACONDA_USER --password $ANACONDA_PWD
- conda build recipe/ 
env:
  global:
  - secure: tDHOREtC3UzNYJcimjb/Es2V0ro0P7mXDLfXoolGlPQcDsIIQZrnRjfHq+lT0M3aYR17oZJAHOJcQ5q2VU1d3SR1X6VeOp3ATOeMUpmGA8OuGAN0s5T3ybCVKOBzKE+O1wSkjO8YhxJ+NCeYfG9bB+f6w7mfb76z3QfIkCdQRcCpGu7ooAmx3MH6U/4BFmCoDIRH6Wji7E4dhcSw9bFd8AUN99POONkpNsFQI2Lt5LuVdVxbsulMbEqqkO9kMlBO3PMyFEteH9ACg1wIyRebw2KcCuRTXZwTSTfXfLdr2KZWYzAn7vG0BtJef5p1d97Wkzmsjs9y/epVvILDE8MjV2IO38mR6/KrHmmyuiEZcK142sx7IP123qMvNUuwG3ifbCiILTzSW++ItnpvRl2r7z1p/p4BwAFyAHbuUH8OXb2hLkZZd28v1OVnCXMR0qexsLSFGP91UjhbrL8zRTWFNoVgoMvMKOGVRMXhNgzGcsL7BVxaLdRU0/CJXIYLl6+vPL9ZElYUmVTPpMVLwqjoBcbPY25EiqwLUbRPu9d9I2WrHatpu+1XXysEO12jJuUj6xc44hVCiQMfzG3NW7qONukxbcibKeJsDlgFPzfb+1S2MFtZWRWFksrjZOawop5lqBzQgILPkmN6nDMzD7GLzKuiPSeSUt6Fd6soJ1Yij78=
  - secure: D5FlXh8iubjhXzfRx5CZEPGCBxkpDofZ2Z5jUQSTedymZQqxXKHkDEx36LP+S36tkPSFqMbm4caBFVRNAXTKbBDN3bjfqHFGIRouSqJg4MG+M8fGBEux14mGzNxuOqB3G/EOXv9yUj16OEGvMiMT6HpOuO053keu0wHQxedNOS/g/oijP3HL9tyIWud/8M9/lghT5ebN6zA2l77BBIUF4j6TIu05+nOIDUAiiivL7SIOjweLTQG7ajQ0Q1ADsQ6vAolasZPmkrG67KtCw+noBPKhmUPvJ951+Wx1B/d37TgyUKa8B0PDbOWohvg7J6XD2kxjKdkjkrzaKGgLhkb6ZXDH2Es8rVtUAIk1JjRsbJXzgZ55ORRiocx73OZOhoIxi5/JZ+3YQjKvCYbzA82N8u38sp8yZAXU0sC6ocbTPUpM9WdfjFu7xwfKtofDbLAgqZh7GDKh7+gxZjNEcJZt4USy43L4U0xyVUrzB6BMbcgo3WwuQ4eR6hXAiTsWBI7G8OOlg/TSrpZEnP4d9wljEB7aOCjY3fc5OIhEWPOaWTrlV/++/8jnyOcbaOz2OOtOx8cT6FlMk7pJVU5MjZReoWQlY8tCud+b7eC9+oxJfuntUss6nRizPpKSEGiPiw2O90vGaBb2LhH0l72MK+otqiZPAXzJXrhgIOn4f5KUoeA=
