language: python

python:
- 2.7

install:
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
- bash Miniconda-latest-Linux-x86_64.sh -b -p ~/miniconda2
- pip install coveralls
- pip install pytest-cov
- conda install pandas
- pip install mock==2.0

script:
- py.test tests -s

after_success:
- coveralls
